# Generated by Django 4.2.18 on 2026-04-25 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('USER', 'Utilisateur')], default='USER', max_length=20, verbose_name='Rôle')),
                ('verification_token', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'core_user',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du département')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom de la direction')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_direction',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('model', models.CharField(blank=True, default='', max_length=200, verbose_name='Modèle')),
                ('internal_id', models.CharField(max_length=50, unique=True, verbose_name='ID interne')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro de série')),
                ('condition', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USAGE', 'Usagé'), ('DEFECTUEUX', 'Défectueux'), ('HORS_SERVICE', 'Hors service')], default='BON', max_length=20, verbose_name='État')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'core_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('action_type', models.CharField(choices=[('ENTREE', 'Entrée'), ('PRET', 'Prêt'), ('RETOUR', 'Retour'), ('SORTIE', 'Sortie')], max_length=10, verbose_name="Type d'action")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Remarques')),
                ('assigned_to', models.ForeignKey(blank=True, help_text="Personne ayant reçu l'équipement (obligatoire pour PRET/SORTIE)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_completed', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Département')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction', verbose_name='Direction')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.equipment', verbose_name='Équipement')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'db_table': 'core_movement',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.direction', verbose_name='Direction'),
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du sous-département')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='core.department', verbose_name='Département')),
            ],
            options={
                'db_table': 'core_subdepartment',
                'ordering': ['name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('direction', 'name')},
        ),
    ]
